# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 357423ccdeff0a19a29959540a6d4013bfc52337ed6950d7bd71a1c0e35b0993478f60549ec8c0749689daed53455f7029b69e63fdf63cb57dc8a001e9ce6178

test:
  secret_key_base: 0032bbbed46f288246773636fd803d9c0717764774fa3bc4a3b7053251df12e58cf9487e7c63185121430358c69d68894ce28e1a359575ca0965b9933f8697da

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
